
from initial_condition_functions import writing_initial_conditions
import os

vtu_filename = "out.50_particles.vtu" # the last vtu file generated by the previous simulation

writing_initial_conditions(vtu_filename,
    decimals=5,
    dimension='3D',
    directory_txt=os.path.abspath("./txt_equation"),
    directory_vtu=os.path.abspath("./vtu_file")
    
     )
